### PR TITLE
Disable Renovate

### PR DESCRIPTION
**Pull request by jasonappah**
Renovate is getting a little spammy across all of our repos so we're disabling it. Maybe later we bring it back with a lower frequency/have it batch dependency updates together?

### CODE REVIEW

**Comment by cjdenio** [comment]
Looks like you made a bunch of other documentation changes, was this a mistake?

**Comment by jasonappah** [comment]
whoops i meant to make those in a separate pr, gimme a sec

**Comment by jasonappah** [comment]
ok so i just force pushed the other commits off this pr... idk why build just failed so i'll look into that later

**Review by anirudhb — APPROVED** [review]

**Comment by anirudhb** [comment]
Hope you don't mind me merging

**Pull request merged**
