### PR TITLE
Switch to mdbook

### PR DESCRIPTION
**Pull request by anirudhb**
Rust is fast

### CODE REVIEW

**Comment by sampoder** [comment]
Rust is fast but do you have any photos of how it'd look?

**Comment by anirudhb** [comment]
Sure:
image
image
image

@sampoder we can also add themes later if necessary and it's a very mature site generator in comparison to Nextra

**Comment by sampoder** [comment]
Hmm alright, does it support MDX or something like MDX?

**Comment by anirudhb** [comment]
No it's markdown

**Review by jasonappah — APPROVED** [review]

**Review by cjdenio — APPROVED** [review]

**Pull request merged**
